export const productsArray = [
    {
      id: 22,
      imageSrc: "/FotosDefinitivas/1.png",
      category: "Botas",
      price: 170000,
      name: "Botas 1",
      description: "Botas en cuero text 100% garantizado.",
    },
    {
      id: 23,
      imageSrc: "/FotosDefinitivas/2.png",
      category: "Botas",
      price: 150000,
      name: "Botas 2",
      description: "Botas en cuero text 100% garantizado.",
    },
    {
      id: 24,
      imageSrc: "/FotosDefinitivas/3.png",
      category: "Botas",
      price: 170000,
      name: "Botas 3",
      description: "Botas en cuero text 100% garantizado.",
    },
    {
      id: 25,
      imageSrc: "/FotosDefinitivas/4.png",
      category: "Botas",
      price: 170000,
      name: "Botas 4",
      description: "Botas en cuero text 100% garantizado.",
    },
    {
      id: 26,
      imageSrc: "/FotosDefinitivas/5.png",
      category: "Botas",
      price: 170000,
      name: "Botas 5",
      description: "Botas en cuero text 100% garantizado.",
    },
    {
      id: 27,
      imageSrc: "/FotosDefinitivas/6.png",
      category: "Botas",
      price: 170000,
      name: "Botas 6",
      description: "Botas en cuero text 100% garantizado.",
    },
    {
      id: 28,
      imageSrc: "/FotosDefinitivas/7.png",
      category: "Botas",
      price: 170000,
      name: "Botas 7",
      description: "Botas en cuero text 100% garantizado.",
    },
    {
      id: 29,
      imageSrc: "/FotosDefinitivas/8.png",
      category: "Botas",
      price: 170000,
      name: "Botas 8",
      description: "Botas en cuero text 100% garantizado.",
    },
    {
      id: 30,
      imageSrc: "/FotosDefinitivas/9.png",
      category: "Botas",
      price: 170000,
      name: "Botas 9",
      description: "Botas en cuero text 100% garantizado.",
    },
    {
      id: 31,
      imageSrc: "/FotosDefinitivas/10.png",
      category: "Botas",
      price: 170000,
      name: "Botas 10",
      description: "Botas en cuero text 100% garantizado.",
    },
    {
      id: 32,
      imageSrc: "/FotosDefinitivas/11.png",
      category: "Botas",
      price: 170000,
      name: "Botas 11",
      description: "Botas en cuero text 100% garantizado.",
    },
    {
      id: 33,
      imageSrc: "/FotosDefinitivas/12.png",
      category: "Botas",
      price: 170000,
      name: "Botas 12",
      description: "Botas en cuero text 100% garantizado.",
    },
    {
      id: 34,
      imageSrc: "/FotosDefinitivas/13.png",
      category: "Botas",
      price: 170000,
      name: "Botas 13",
      description: "Botas en cuero text 100% garantizado.",
    },
    {
      id: 35,
      imageSrc: "/FotosDefinitivas/14.png",
      category: "Botas",
      price: 170000,
      name: "Botas 14",
      description: "Botas en cuero text 100% garantizado.",
    },
    {
      id: 36,
      imageSrc: "/FotosDefinitivas/15.png",
      category: "Botas",
      price: 170000,
      name: "Botas 15",
      description: "Botas en cuero text 100% garantizado.",
    },
    {
      id: 37,
      imageSrc: "/FotosDefinitivas/16.png",
      category: "Botas",
      price: 170000,
      name: "Botas 16",
      description: "Botas en cuero text 100% garantizado.",
    },
    {
      id: 38,
      imageSrc: "/FotosDefinitivas/17.png",
      category: "Botas",
      price: 170000,
      name: "Botas 17",
      description: "Botas en cuero text 100% garantizado.",
    },
    {
      id: 39,
      imageSrc: "/FotosDefinitivas/18.png",
      category: "Botas",
      price: 170000,
      name: "Botas 18",
      description: "Botas en cuero text 100% garantizado.",
    },
    {
      id: 40,
      imageSrc: "/FotosDefinitivas/19.png",
      category: "Botas",
      price: 170000,
      name: "Botas 19",
      description: "Botas en cuero text 100% garantizado.",
    },
    {
      id: 41,
      imageSrc: "/FotosDefinitivas/20.png",
      category: "Botas",
      price: 170000,
      name: "Botas 20",
      description: "Botas en cuero text 100% garantizado.",
    },
    {
      id: 42,
      imageSrc: "/FotosDefinitivas/21.png",
      category: "Botas",
      price: 170000,
      name: "Botas 21",
      description: "Botas en cuero text 100% garantizado.",
    },
    {
      id: 43,
      imageSrc: "/FotosDefinitivas/22.png",
      category: "Botas",
      price: 170000,
      name: "Botas 22",
      description: "Botas en cuero text 100% garantizado.",
    },
    {
      id: 44,
      imageSrc: "/FotosDefinitivas/23.png",
      category: "Botas",
      price: 170000,
      name: "Botas 23",
      description: "Botas en cuero text 100% garantizado.",
    },
    {
      id: 45,
      imageSrc: "/FotosDefinitivas/24.png",
      category: "Botas",
      price: 170000,
      name: "Botas 24",
      description: "Botas en cuero text 100% garantizado.",
    },
    {
      id: 46,
      imageSrc: "/FotosDefinitivas/25.png",
      category: "Botas",
      price: 170000,
      name: "Botas 25",
      description: "Botas en cuero text 100% garantizado.",
    },
    {
      id: 47,
      imageSrc: "/FotosDefinitivas/26.png",
      category: "Botas",
      price: 170000,
      name: "Botas 26",
      description: "Botas en cuero text 100% garantizado.",
    },
    {
      id: 48,
      imageSrc: "/FotosDefinitivas/27.png",
      category: "Botas",
      price: 170000,
      name: "Botas 27",
      description: "Botas en cuero text 100% garantizado.",
    },
    {
      id: 49,
      imageSrc: "/FotosDefinitivas/28.png",
      category: "Botas",
      price: 170000,
      name: "Botas 28",
      description: "Botas en cuero text 100% garantizado.",
    },
    {
      id: 50,
      imageSrc: "/FotosDefinitivas/29.png",
      category: "Botas",
      price: 170000,
      name: "Botas 29",
      description: "Botas en cuero text 100% garantizado.",
    },
    {
      id: 51,
      imageSrc: "/FotosDefinitivas/30.png",
      category: "Botas",
      price: 170000,
      name: "Botas 30",
      description: "Botas en cuero text 100% garantizado.",
    },
    {
      id: 1,
      imageSrc: "/1.PNG",
      category: "Sets de Lenceria",
      price: 55000,
      name: "Set Negro",
      description: "Juego de lenceria de tres piezas con finos materiales y detalles.",
    },
    {
      id: 20,
      imageSrc: "/pijama3.PNG",
      category: "Pijamas",
      price: 155000,
      name: "Pijama 3",
      description: "Hermosa pijama.",
    },
    {
      id: 21,
      imageSrc: "/pijama4.PNG",
      category: "Pijamas",
      price: 75000,
      name: "Pijama 4",
      description: "Hermosa pijama.",
    },
    {
      id: 2,
      imageSrc: "/VarillaBlanco.PNG",
      category: "Sets de Lenceria",
      price: 58000,
      name: "Set Varilla Blanco",
      description: "Juego de lenceria de tres piezas con finos materiales y detalles.",
    },
    {
      id: 9,
      imageSrc: "/accesorio1.PNG",
      category: "Accesorios",
      price: 210000,
      name: "Accesorio 1",
      description: "Hermoso accesorio.",
    },
    {
      id: 10,
      imageSrc: "/accesorio2.PNG",
      category: "Accesorios",
      price: 89000,
      name: "Accesorio 2",
      description: "Hermoso accesorio.",
    },
    {
      id: 3,
      imageSrc: "/VarillaNegro.PNG",
      category: "Sets de Lenceria",
      price: 5500,
      name: "Set Varilla Negro",
      description: "Juego de lenceria de tres piezas con finos materiales y detalles.",
    },
    {
      id: 4,
      imageSrc: "/NeoRojo.PNG",
      category: "Sets de Lenceria",
      price: 66000,
      name: "Set Neo Rojo",
      description: "Juego de lenceria de tres piezas con finos materiales y detalles.",
    },
    {
      id: 5,
      imageSrc: "/OliviaBicolor.jpeg",
      category: "Sets de Lenceria",
      price: 48000,
      name: "Set Olivia Bicolor",
      description: "Juego de lenceria de tres piezas con finos materiales y detalles.",
    },
    {
      id: 6,
      imageSrc: "/Anastasia.PNG",
      category: "Sets de Lenceria",
      price: 60000,
      name: "Set Anastasia",
      description: "Juego de lenceria de tres piezas con finos materiales y detalles.",
    },
    {
      id: 7,
      imageSrc: "/VarillaLigero.PNG",
      category: "Sets de Lenceria",
      price: 52000,
      name: "Set Varilla Liguero",
      description: "Juego de lenceria de tres piezas con finos materiales y detalles.",
    },
    {
      id: 11,
      imageSrc: "/accesorio3.PNG",
      category: "Accesorios",
      price: 90000,
      name: "Accesorio 3",
      description: "Hermoso accesorio.",
    },
    {
      id: 12,
      imageSrc: "/accesorio4.PNG",
      category: "Accesorios",
      price: 100000,
      name: "Accesorio 4",
      description: "Hermoso accesorio.",
    },
    {
      id: 13,
      imageSrc: "/accesorio5.PNG",
      category: "Accesorios",
      price: 80000,
      name: "Accesorio 5",
      description: "Hermoso accesorio.",
    },
    {
      id: 18,
      imageSrc: "/pijama1.PNG",
      category: "Pijamas",
      price: 95000,
      name: "Pijama 1",
      description: "Hermosa pijama.",
    },
    {
      id: 19,
      imageSrc: "/pijama2.PNG",
      category: "Pijamas",
      price: 195000,
      name: "Pijama 2",
      description: "Hermosa pijama.",
    },
  ];