export const productsArray = [
    {
      id: 14,
      imageSrc: "/botas2.PNG",
      category: "Botas",
      price: 230000,
      name: "Botas 2",
      description: "Hermosas botas.",
    },
    {
      id: 15,
      imageSrc: "/botas3.PNG",
      category: "Botas",
      price: 190000,
      name: "Botas 3",
      description: "Hermosas botas.",
    },
    {
      id: 1,
      imageSrc: "/1.PNG",
      category: "Sets de Lenceria",
      price: 55000,
      name: "Set Negro",
      description: "Juego de lenceria de tres piezas con finos materiales y detalles.",
    },
    {
      id: 18,
      imageSrc: "/pijama3.PNG",
      category: "Pijamas",
      price: 155000,
      name: "Pijama 3",
      description: "Hermosa pijama.",
    },
    {
      id: 18,
      imageSrc: "/pijama4.PNG",
      category: "Pijamas",
      price: 75000,
      name: "Pijama 4",
      description: "Hermosa pijama.",
    },
    {
      id: 2,
      imageSrc: "/VarillaBlanco.PNG",
      category: "Sets de Lenceria",
      price: 58000,
      name: "Set Varilla Blanco",
      description: "Juego de lenceria de tres piezas con finos materiales y detalles.",
    },
    {
      id: 9,
      imageSrc: "/accesorio1.PNG",
      category: "Accesorios",
      price: 210000,
      name: "Accesorio 1",
      description: "Hermoso accesorio.",
    },
    {
      id: 10,
      imageSrc: "/accesorio2.PNG",
      category: "Accesorios",
      price: 89000,
      name: "Accesorio 2",
      description: "Hermoso accesorio.",
    },
    {
      id: 3,
      imageSrc: "/VarillaNegro.PNG",
      category: "Sets de Lenceria",
      price: 5500,
      name: "Set Varilla Negro",
      description: "Juego de lenceria de tres piezas con finos materiales y detalles.",
    },
    {
      id: 4,
      imageSrc: "/NeoRojo.PNG",
      category: "Sets de Lenceria",
      price: 66000,
      name: "Set Neo Rojo",
      description: "Juego de lenceria de tres piezas con finos materiales y detalles.",
    },
    {
      id: 5,
      imageSrc: "/OliviaBicolor.jpeg",
      category: "Sets de Lenceria",
      price: 48000,
      name: "Set Olivia Bicolor",
      description: "Juego de lenceria de tres piezas con finos materiales y detalles.",
    },
    {
      id: 6,
      imageSrc: "/Anastasia.PNG",
      category: "Sets de Lenceria",
      price: 60000,
      name: "Set Anastasia",
      description: "Juego de lenceria de tres piezas con finos materiales y detalles.",
    },
    {
      id: 7,
      imageSrc: "/VarillaLigero.PNG",
      category: "Sets de Lenceria",
      price: 52000,
      name: "Set Varilla Liguero",
      description: "Juego de lenceria de tres piezas con finos materiales y detalles.",
    },
    {
      id: 8,
      imageSrc: "/Vaqueras1.PNG",
      category: "Botas",
      price: 230000,
      name: "Botas Vaqueras 1",
      description: "Hermosas botas en tendencia.",
    },
    {
      id: 11,
      imageSrc: "/accesorio3.PNG",
      category: "Accesorios",
      price: 90000,
      name: "Accesorio 3",
      description: "Hermoso accesorio.",
    },
    {
      id: 12,
      imageSrc: "/accesorio4.PNG",
      category: "Accesorios",
      price: 100000,
      name: "Accesorio 4",
      description: "Hermoso accesorio.",
    },
    {
      id: 13,
      imageSrc: "/accesorio5.PNG",
      category: "Accesorios",
      price: 80000,
      name: "Accesorio 5",
      description: "Hermoso accesorio.",
    },
    {
      id: 16,
      imageSrc: "/botas4.PNG",
      category: "Botas",
      price: 1450000,
      name: "Botas 4",
      description: "Hermosas botas.",
    },
    {
      id: 17,
      imageSrc: "/botas5.PNG",
      category: "Botas",
      price: 178000,
      name: "Botas 5",
      description: "Hermosas botas.",
    },
    {
      id: 18,
      imageSrc: "/pijama1.PNG",
      category: "Pijamas",
      price: 95000,
      name: "Pijama 1",
      description: "Hermosa pijama.",
    },
    {
      id: 18,
      imageSrc: "/pijama2.PNG",
      category: "Pijamas",
      price: 195000,
      name: "Pijama 2",
      description: "Hermosa pijama.",
    },
  ];